# Generated by Django 4.2.21 on 2026-04-16 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(verbose_name='매물 설명')),
                ('property_type', models.CharField(choices=[('apartment', '아파트'), ('villa', '빌라'), ('officetel', '오피스텔'), ('oneroom', '원룸'), ('store', '상가'), ('land', '토지')], max_length=20, verbose_name='매물유형')),
                ('trade_type', models.CharField(choices=[('sale', '매매'), ('jeonse', '전세'), ('monthly', '월세')], max_length=10, verbose_name='거래유형')),
                ('price', models.PositiveIntegerField(verbose_name='매매가/전세금(만원)')),
                ('deposit', models.PositiveIntegerField(blank=True, null=True, verbose_name='보증금(만원)')),
                ('monthly_rent', models.PositiveIntegerField(blank=True, null=True, verbose_name='월세(만원)')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='면적(m2)')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('address_detail', models.CharField(blank=True, max_length=100, verbose_name='상세주소')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='층수')),
                ('rooms', models.PositiveSmallIntegerField(default=1, verbose_name='방 수')),
                ('bathrooms', models.PositiveSmallIntegerField(default=1, verbose_name='화장실 수')),
                ('direction', models.CharField(blank=True, choices=[('east', '동향'), ('west', '서향'), ('south', '남향'), ('north', '북향'), ('southeast', '남동향'), ('southwest', '남서향'), ('northeast', '북동향'), ('northwest', '북서향')], max_length=10, verbose_name='방향')),
                ('heating', models.CharField(blank=True, choices=[('individual', '개별난방'), ('central', '중앙난방'), ('district', '지역난방')], max_length=20, verbose_name='난방')),
                ('parking', models.BooleanField(blank=True, null=True, verbose_name='주차 가능')),
                ('maintenance_fee', models.PositiveIntegerField(blank=True, null=True, verbose_name='관리비(만원)')),
                ('available_date', models.DateField(blank=True, null=True, verbose_name='입주가능일')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '승인'), ('rejected', '반려'), ('completed', '거래완료')], default='pending', max_length=20, verbose_name='상태')),
                ('is_available', models.BooleanField(default=True, verbose_name='거래 가능')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '매물',
                'verbose_name_plural': '매물',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', '허위매물'), ('inappropriate', '부적절한 내용'), ('fraud', '사기 의심'), ('completed', '이미 거래완료'), ('other', '기타')], max_length=20, verbose_name='사유')),
                ('description', models.TextField(blank=True, verbose_name='상세 사유')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('resolved', '처리완료'), ('dismissed', '기각')], default='pending', max_length=20, verbose_name='처리상태')),
                ('admin_note', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.property', verbose_name='매물')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '신고',
                'verbose_name_plural': '신고',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/', verbose_name='이미지')),
                ('is_thumbnail', models.BooleanField(default=False, verbose_name='대표이미지')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.property', verbose_name='매물')),
            ],
            options={
                'verbose_name': '매물 이미지',
                'verbose_name_plural': '매물 이미지',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='listings.property', verbose_name='매물')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'trade_type'], name='listings_pr_propert_9b05d4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='listings_pr_status_de90a3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='listings_pr_created_e6aabb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'property')},
        ),
    ]
