# Generated by Django 4.2.21 on 2026-04-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_property_author_alter_property_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', '아파트'), ('house', '단독/다가구'), ('villa', '연립/빌라'), ('oneroom', '방한칸'), ('office', '사무실/오피스텔'), ('restaurant', '요식업/영업점'), ('store', '상가점포/빌딩'), ('land', '대지/임야'), ('factory', '공장/창고/기타')], max_length=20, verbose_name='매물유형'),
        ),
    ]
