# Generated by Django 4.2.21 on 2026-04-20 01:44

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_property_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('apartment', '아파트'), ('house', '단독/다가구'), ('villa', '연립/빌라'), ('oneroom', '방한칸'), ('office', '사무실/오피스텔'), ('restaurant', '요식업/영업점'), ('store', '상가점포/빌딩'), ('land', '대지/임야'), ('factory', '공장/창고/기타')], max_length=20, verbose_name='분류')),
                ('writer_name', models.CharField(max_length=30, verbose_name='작성자')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='글내용')),
                ('file1', models.FileField(blank=True, upload_to=listings.models.board_file_path, verbose_name='파일첨부')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '매물 게시판',
                'verbose_name_plural': '매물 게시판',
                'ordering': ['-created_at'],
            },
        ),
    ]
