# Generated by Django 4.2.21 on 2026-04-20 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0004_boardpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_posts', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='비밀번호'),
        ),
    ]
