# Generated by Django 4.2.21 on 2026-04-20 01:58

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_boardpost_author_alter_boardpost_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=listings.models.board_file_path, verbose_name='파일')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='원본 파일명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='listings.boardpost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시판 첨부파일',
                'verbose_name_plural': '게시판 첨부파일',
                'ordering': ['created_at'],
            },
        ),
    ]
